**Exercise 5.3** 

The goal of this exercise is to implement a Turing machine.
1. Read about Turing machines at http://thinkcomplex.com/tm.
2. Write a class called Turing that implements a Turing machine. For the
action table, use the rules for a 3-state busy beaver.

3. Write a class named TuringViewer that generates an image that represents the state of the tape and the position and state of the head. For one example of what that might look like, see http://thinkcomplex.com/turing.

In [ ]:
class Turing:
# https://www.matesfacil.com/automatas-lenguajes/Maquina-Turing.html

    def __init__(self, Q, Gamma, b, Sigma, delta, q0, F):
        self.Q = Q
        self.Gamma = Gamma
        self.b = b
        self.Sigma = Sigma
        self.delta = delta
        self.q0 = q0
        self.F = F
    
    def func_delta(self, q, simbolo): 
        #func de transicion -> δ(q,X) = (p,Y,{L, R})

        # simbolo 0 y estado A
        if q == "A" and simbolo == 0:
            return "B", 1, "R"
            
        # simbolo 0 y estado B
        if q == "B" and simbolo == 0:
            return "A", 1, "L"

        # simbolo 0 y estado C
        if q == "C" and simbolo == 0:
            return "B", 1, "L"

        # simbolo 1 y estado A
        if q == "A" and simbolo == 1:
            return "C", 1, "L"        

        # simbolo 1 y estado B
        if q == "B" and simbolo == 1:
            return "B", 1, "R"

        # simbolo 1 y estado B
        if q == "C" and simbolo == 1:
            return "H", 1, "R"


    def corre_maquina(self):
        acciones = []
        i = 0
        while self.q0 != "H" and i < len(self.Sigma):
            actual = self.q0
            simbolo_actual = self.Sigma[i]
            self.q0, self.Sigma[i], direc = self.func_delta(self.q0,
                                                            self.Sigma[i])
            acciones.append([actual, simbolo_actual,self.Sigma[i], direc,
                             self.q0])
            i+=1
        print(acciones)


In [453]:
# cadenas que terminan en estado H -> [0, 0, 1, 1], [1, 1, 0, 1]
Q, Gamma, b, Sigma, q0, F = ["A", "B", "C", "H"], [0, 1], 0, [1, 0, 0, 0], "A", "H"
maquina = Turing(Q, Gamma, b, Sigma, delta, q0, F)

maquina.corre_maquina()


[['A', 1, 1, 'L', 'C'], ['C', 0, 1, 'L', 'B'], ['B', 0, 1, 'L', 'A'], ['A', 0, 1, 'R', 'B']]


**Exercise 6.5**

If you generalize the Turing machine to two dimensions, or
add a read-write head to a 2-D CA, the result is a cellular automaton called a Turmite. It is named after a termite because of the way the read-write head moves, but spelled wrong as an homage to Alan Turing.

The most famous Turmite is Langton’s Ant, discovered by Chris Langton in 1986. See http://thinkcomplex.com/langton.

The ant is a read-write head with four states, which you can think of as facing north, south, east or west. The cells have two states, black and white.

The rules are simple. During each time step, the ant checks the color of the cell it is on. If black, the ant turns to the right, changes the cell to white, and moves forward one space. If the cell is white, the ant turns left, changes the cell to black, and moves forward.

Given a simple world, a simple set of rules, and only one moving part, you might expect to see simple behavior — but you should know better by now.Starting with all white cells, Langton’s ant moves in a seemingly random pattern for more than 10,000 steps before it enters a cycle with a period of 104 steps. After each cycle, the ant is translated diagonally, so it leaves a trail called the “highway”.

**Write an implementation of Langton’s Ant.**


In [ ]:
from matplotlib import animation
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from scipy import signal
import itertools 
from scipy.signal import correlate2d

In [ ]:

class Langton():

    def __init__(self, a, b):
        self.x, self.y = a, b # posicion de inicio de la hormiga
        
    def inicia(self):
        return np.zeros((self.x, self.y))

    def direcciones(self, grid, x, y, R):

        # norte
        if(R == " " and grid[x, y] == 0):
            #grid[x, y] = grid[x - 1, y]
            grid[x, y] = 1
            return grid, x-1, y
        # sur
        #grid[x, y] = grid[x + 1, y]
        
        #este
        #grid[x, y] = grid[x, y + 1]
        
        #oeste
        #grid[x, y] = grid[x, y - 1]

        return grid

    def mov(self, iters):
        malla = self.inicia()
        a, b = int(n/2) , int(m/2)
        #print(malla)
        if malla[a, b] == 0:
            malla, x, y = self.direcciones(malla, a, b, " ")
            print(malla, x, y)



In [452]:
n, m = 16, 16
ant = Langton(n, m)

ant.mov(2)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 7 8


In [ ]:
#fig, ax = plt.subplots(figsize=(10, 10))
#imagen = ax.imshow(malla, vmin=0, vmax=1)
#ax.set_axis_off()

**Exercise 7.2**

In 1990 Bak, Chen and Tang proposed a cellular automaton
that is an abstract model of a forest fire. Each cell is in one of three states:
empty, occupied by a tree, or on fire.

The rules of the CA are:
1. An empty cell becomes occupied with probability p.
2. A cell with a tree burns if any of its neighbors is on fire.
3. A cell with a tree spontaneously burns, with probability f, even if none
of its neighbors is on fire.
4. A cell with a burning tree becomes an empty cell in the next time step.

Write a program that implements this model. You might want to inherit from Cell2D. Typical values for the parameters are p = 0.01 and f = 0.001, but you might want to experiment with other values.

Starting from a random initial condition, run the model until it reaches a steady state where the number of trees no longer increases or decreases consistently.

In steady state, is the geometry of the forest fractal? What is its fractal dimension?